// Package skill renders and locates the agent skill file that `bk skill install`
// writes.
//
// The design constraint that shapes everything here: the skill must contain NO
// facts that can rot. It is a pointer — "run `bk guide`, run `bk meta`" — not a
// copy. That is why it is identical for every user and essentially never needs
// to change, and why a stale copy is harmless rather than actively misleading.
//
// The only thing that varies is the trailing version stamp, which `bk skill
// check` reads to tell whether the installed file came from this binary.
//
// OWNERSHIP. `bk skill sync` is the one command agents are told to run
// unprompted, so writing must never destroy something a human wrote. The block
// bk owns is delimited by markers; anything outside them — added front matter,
// team rules appended below — is preserved across every install and sync. A file
// with neither the markers nor the legacy stamp was NOT written by bk, and bk
// refuses to touch it (see Classify / ErrForeign).
package skill

import (
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

//go:embed template.md
var template string

// Name is the skill's directory/identifier under .claude/skills/.
//
// `blackcode`, not `blackcode-issues`, since 2.0.0 (D-17). NOT COSMETIC: an
// agent scanning the available skills, seeing one called "blackcode-issues"
// while it has been asked to do sales work, and concluding "not my job" is the
// single failure this file exists to prevent. The skill describes the CLI, and
// the CLI drives every app.
const Name = "blackcode"

// LegacyName is what the skill was called before 2.0.0. It survives in three
// places and each has a different reason:
//
//   - the installed DIRECTORY, which `bk skill sync` migrates (see MigrateFrom);
//   - the block markers, which `Classify` must keep recognising or every file
//     installed by an older bk becomes Foreign — and a Foreign file is one
//     `sync` refuses to touch, so renaming the markers naively would have
//     turned "we renamed a skill" into "every agent's skill silently froze";
//   - nothing else. It is not a fallback for lookups.
const LegacyName = "blackcode-issues"

// stampRe matches the trailing provenance comment, e.g.
// `<!-- generated by bk skill install · cli 1.9.0 · do not edit -->`.
var stampRe = regexp.MustCompile(`<!--\s*generated by bk skill install\s*·\s*cli\s+([^\s·]+)\s*·[^>]*-->`)

// Render returns a complete SKILL.md: the YAML front matter, then the delimited
// block bk owns.
//
// The front matter is deliberately OUTSIDE the markers. Skill loaders require it
// at the very top of the file, so a leading HTML comment would break parsing —
// and it also means a user may retitle or re-describe the skill without bk
// reverting it on the next sync.
func Render(version string) string {
	fm, body := splitFrontMatter(strings.TrimSpace(template))
	if fm == "" {
		return renderBlock(body, version)
	}
	return fm + "\n\n" + renderBlock(body, version)
}

// renderBlock returns the marked, version-stamped region.
func renderBlock(body, version string) string {
	return fmt.Sprintf("%s\n%s\n\n<!-- generated by bk skill install · cli %s · do not edit -->\n%s\n",
		blockBegin, strings.TrimSpace(body), version, blockEnd)
}

// splitFrontMatter separates a leading `---` YAML block from the body.
func splitFrontMatter(doc string) (frontMatter, body string) {
	if !strings.HasPrefix(doc, "---") {
		return "", doc
	}
	i := strings.Index(doc[3:], "\n---")
	if i < 0 {
		return "", doc
	}
	end := 3 + i + 4
	return strings.TrimSpace(doc[:end]), strings.TrimSpace(doc[end:])
}

// Ownership says who wrote the file bk is about to overwrite.
type Ownership int

const (
	// Absent — no file, or an empty one. Safe to create.
	Absent Ownership = iota
	// Managed — carries bk's markers. Only the marked region is replaced.
	Managed
	// Legacy — written by bk 1.9.0, which stamped but did not delimit. Every
	// byte of it came from bk, so it is safe to rewrite wholesale (which also
	// migrates it to the marked format).
	Legacy
	// Foreign — neither marker nor stamp. A human wrote this. Never touch it.
	Foreign
)

// ErrForeign is returned when the target was not written by bk.
var ErrForeign = errors.New("skill file was not written by bk")

// Classify reports who owns an existing skill file's content.
func Classify(content string) Ownership {
	if strings.TrimSpace(content) == "" {
		return Absent
	}
	if _, _, ok := findBlock(content); ok {
		return Managed
	}
	if stampRe.MatchString(content) {
		return Legacy
	}
	return Foreign
}

// findBlock locates bk's delimited region, under EITHER the current markers or
// the pre-2.0.0 ones, and reports where it starts and ends.
//
// Accepting both is the whole of the marker migration. A file written by bk
// 2.0.0 carries `blackcode-issues` markers; if `Classify` only knew the new
// spelling it would call that file Foreign, and `sync` — the one command agents
// run unprompted — would decline to update it and print a warning about
// hand-written content that nobody wrote. The file would freeze at whatever
// version installed it, quietly, forever.
//
// The write path always emits the CURRENT markers, so a file converts on its
// first sync and this branch is dead for it thereafter.
func findBlock(content string) (start, end int, ok bool) {
	for _, m := range []struct{ begin, end string }{
		{blockBegin, blockEnd},
		{legacyBlockBegin, legacyBlockEnd},
	} {
		s := strings.Index(content, m.begin)
		e := strings.Index(content, m.end)
		if s >= 0 && e > s {
			return s, e + len(m.end), true
		}
	}
	return 0, 0, false
}

// UpsertSkillFile returns the new SKILL.md content for an existing file.
//
// It returns ErrForeign — and never a partial write — when the file was written
// by someone other than bk. Callers decide what that means: `install` refuses
// unless --force, `sync` leaves the file alone and warns.
func UpsertSkillFile(existing, version string) (string, error) {
	switch Classify(existing) {
	case Absent, Legacy:
		return Render(version), nil
	case Managed:
		start, end, ok := findBlock(existing)
		if !ok {
			return "", ErrForeign
		}
		_, body := splitFrontMatter(strings.TrimSpace(template))
		block := strings.TrimRight(renderBlock(body, version), "\n")
		// Always writes the CURRENT markers, whichever pair it found — which is
		// what converts a pre-2.0.0 file in place, without a separate migration
		// step and without disturbing a byte outside the block.
		return existing[:start] + block + existing[end:], nil
	default:
		return "", ErrForeign
	}
}

// StampedVersion extracts the CLI version from an installed skill file's stamp.
// Returns "" when the file has no stamp (hand-written, or from a pre-1.9 CLI).
func StampedVersion(content string) string {
	if m := stampRe.FindStringSubmatch(content); m != nil {
		return m[1]
	}
	return ""
}

// --- AGENTS.md container -----------------------------------------------------

// Markers delimiting the region bk owns. Shared by SKILL.md and the AGENTS.md
// section so both containers behave identically: a re-run replaces what is
// between them and leaves everything else alone.
const (
	blockBegin = "<!-- BEGIN blackcode (managed by bk skill install) -->"
	blockEnd   = "<!-- END blackcode -->"

	// The pre-2.0.0 pair. READ-ONLY: `findBlock` still recognises these so an
	// older file stays Managed, and nothing writes them again.
	legacyBlockBegin = "<!-- BEGIN blackcode-issues (managed by bk skill install) -->"
	legacyBlockEnd   = "<!-- END blackcode-issues -->"
)

// BlockBegin and BlockEnd are exported so commands can print them verbatim: the
// fix for a foreign file is "paste these two lines in", which is only actionable
// if the error message contains the exact strings.
const (
	BlockBegin = blockBegin
	BlockEnd   = blockEnd
)

// RenderAgentsSection returns the delimited `## blackcode issues` block that
// `bk skill install --format agents-md` writes into ./AGENTS.md. Same content,
// different container — the markers let a re-run update it in place instead of
// appending a second copy.
func RenderAgentsSection(version string) string {
	// Drop the YAML front matter — AGENTS.md is prose, not a skill manifest.
	_, body := splitFrontMatter(strings.TrimSpace(template))
	// Demote every heading one level so `# blackcode issues` nests under the
	// host document's structure.
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "#") {
			lines[i] = "#" + l
		}
	}
	return fmt.Sprintf("%s\n%s\n\n<!-- bk %s -->\n%s\n",
		blockBegin, strings.Join(lines, "\n"), version, blockEnd)
}

// UpsertAgentsSection replaces the delimited block in doc, or appends it when
// there isn't one yet. Recognises the pre-2.0.0 markers too, so an AGENTS.md
// written by an older bk is updated in place rather than gaining a second copy.
func UpsertAgentsSection(doc, section string) string {
	if start, end, ok := findBlock(doc); ok {
		return doc[:start] + strings.TrimRight(section, "\n") + doc[end:]
	}
	if strings.TrimSpace(doc) == "" {
		return section
	}
	return strings.TrimRight(doc, "\n") + "\n\n" + section
}

// --- target resolution -------------------------------------------------------

// DefaultDir picks where the skill file goes:
//
//	./.claude/skills/blackcode/   when a .claude/ exists in cwd or an ancestor
//	                              (project-local install)
//	~/.claude/skills/blackcode/   otherwise (user-global install)
//
// Preferring the project-local directory matters: an agent working in a repo
// should get the skill that repo's collaborators see, not one user's global copy.
func DefaultDir() (string, error) {
	if root, ok := findClaudeDir(); ok {
		return filepath.Join(root, "skills", Name), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "skills", Name), nil
}

// findClaudeDir walks up from the working directory looking for a `.claude`
// directory, returning its path.
func findClaudeDir() (string, bool) {
	dir, err := os.Getwd()
	if err != nil {
		return "", false
	}
	for {
		candidate := filepath.Join(dir, ".claude")
		if fi, err := os.Stat(candidate); err == nil && fi.IsDir() {
			return candidate, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

// FilePath returns the SKILL.md path inside a skill directory.
func FilePath(dir string) string {
	return filepath.Join(dir, "SKILL.md")
}

// LegacyDir returns where a pre-2.0.0 bk would have installed, given where this
// one does: the same `skills/` parent, under the old name.
//
// Derived from the target rather than resolved independently so that `--dir`,
// the project-local `.claude/` and the user-global `~/.claude/` all migrate the
// copy that sits BESIDE the one being written, and never some other user's.
func LegacyDir(dir string) string {
	return filepath.Join(filepath.Dir(dir), LegacyName)
}

// MigrationPlan is what `bk skill sync` would do about a pre-2.0.0 install.
//
// A plan rather than an action because this is the destructive path: `sync` runs
// unattended, on an agent's own initiative, and the one thing it must never do
// is delete something a human wrote. Separating "decide" from "do" is what lets
// the decision be tested without a filesystem, and what lets the command report
// WHAT it moved rather than only that it moved something.
type MigrationPlan struct {
	// Content is what to write at the new path — the old file's user additions
	// carried through, not a fresh render, so team rules survive the move.
	Content string
	// RemoveOld is false when there is nothing to do at all.
	RemoveOld bool
}

// PlanMigration decides what to do about an old install sitting beside the new
// target. `newContent` is empty when the new path has no file yet.
//
// It returns an empty plan — do nothing — in every case except the one that
// matters: nothing at the new path, something bk owns at the old one. In
// particular, once the new file exists the old one is no longer consulted, which
// is what makes a second `sync` a no-op instead of a second migration.
//
// ErrForeign means the old file was hand-written. Do not move it, do not delete
// it, and do not write a second skill beside it either: two skills claiming the
// same tool is a worse outcome than one with a stale name.
func PlanMigration(oldContent, newContent, version string) (MigrationPlan, error) {
	if strings.TrimSpace(newContent) != "" || strings.TrimSpace(oldContent) == "" {
		return MigrationPlan{}, nil
	}
	content, err := UpsertSkillFile(oldContent, version)
	if err != nil {
		return MigrationPlan{}, err
	}
	return MigrationPlan{Content: renameFrontMatter(content), RemoveOld: true}, nil
}

// renameFrontMatter rewrites `name: blackcode-issues` to `name: blackcode`.
//
// THE MIGRATION IS INCOMPLETE WITHOUT IT, and the reason is easy to miss: the
// front matter sits OUTSIDE bk's managed block on purpose, so that a user may
// retitle or re-describe the skill without bk reverting it. That protection is
// right for the description and wrong for the identity — a file moved into
// `skills/blackcode/` while still declaring `name: blackcode-issues` is a skill
// the LOADER goes on advertising under the old name. Directory renamed, nothing
// renamed. Caught by moving a real file and reading it.
//
// So this is deliberately the narrowest edit that fixes it:
//
//   - only during a migration, never on an ordinary install or sync;
//   - only when the value is EXACTLY the old name. A user who renamed it to
//     something of their own keeps their name — that is the choice the front
//     matter's position exists to protect, and this is not it. bk chose
//     `blackcode-issues`, so bk may change it.
func renameFrontMatter(content string) string {
	fm, _ := splitFrontMatter(strings.TrimSpace(content))
	if fm == "" {
		return content
	}
	for _, form := range []string{"name: " + LegacyName, "name: \"" + LegacyName + "\"", "name: '" + LegacyName + "'"} {
		if strings.Contains(fm, form+"\n") {
			return strings.Replace(content, form+"\n", "name: "+Name+"\n", 1)
		}
	}
	return content
}
